name:                hask-trpg
version:             0.1.0.0
github:              "bruno-cadorette/hask-trpg"
license:             BSD3
author:              "Bruno Cadorette"
copyright:           "2019 Bruno Cadorette"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bruno-cadorette/hask-trpg#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- servant-js
- warp
- containers
- aeson
- mtl
- stm
- lucid
- servant-lucid
- array
- lens
- servant-checked-exceptions
- polysemy
- polysemy-plugin
- http-types
- servant-foreign
- servant-auth-server
- hspec
- gdp
- range  >= 0.3.0.2

library:
  source-dirs: src 
  ghc-options: 
  - -O2 
  - -flate-specialise 
  - -fspecialise-aggressively

executables:
  hask-trpg-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - hask-trpg
    ghc-options: 
    - -O2 
    - -flate-specialise 
    - -fspecialise-aggressively
    default-extensions:
    - DataKinds
    - FlexibleContexts
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators

tests:
  hask-trpg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - hask-trpg
